language: node_js
node_js:
  - "8.1.2"

dist: trusty

install:
  - npm install

before_install:
  - npm install react-scripts -g

script:
  - ./node_modules/.bin/eslint src/App.js
  - npm run-script build